/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data_secure;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class decrypt extends javax.swing.JFrame {

    /**
     * Creates new form decrypt
     */
    public decrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filepath = new javax.swing.JTextField();
        choose_file = new javax.swing.JButton();
        secrect_key = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        decrypt_file = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1014, 591));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Secure Your Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 640, 60));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Encrypt Your File");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        filepath.setEditable(false);
        filepath.setBackground(new java.awt.Color(204, 204, 204));
        filepath.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        filepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filepathActionPerformed(evt);
            }
        });
        getContentPane().add(filepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 300, 40));

        choose_file.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        choose_file.setForeground(new java.awt.Color(255, 0, 0));
        choose_file.setText("Select Your File");
        choose_file.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        choose_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose_fileActionPerformed(evt);
            }
        });
        getContentPane().add(choose_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 180, 40));

        secrect_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secrect_keyActionPerformed(evt);
            }
        });
        getContentPane().add(secrect_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 300, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(Enter a 16 Digit Secrect Key)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, -1, 30));

        decrypt_file.setBackground(new java.awt.Color(255, 102, 102));
        decrypt_file.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        decrypt_file.setForeground(new java.awt.Color(204, 0, 0));
        decrypt_file.setText("Decrypt");
        decrypt_file.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decrypt_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypt_fileActionPerformed(evt);
            }
        });
        getContentPane().add(decrypt_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 170, 40));

        back.setBackground(new java.awt.Color(0, 153, 255));
        back.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data_secure/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filepathActionPerformed

    private void choose_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        filepath.setText(f.getAbsolutePath());

    }//GEN-LAST:event_choose_fileActionPerformed

    private void secrect_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secrect_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secrect_keyActionPerformed

    private void decrypt_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypt_fileActionPerformed
       
        try{
            FileInputStream file = new FileInputStream(filepath.getText());
            FileOutputStream outStream = new FileOutputStream("D:\\Decrypted_File.txt");
            byte []k = (secrect_key.getText()).getBytes();
            SecretKeySpec key = new SecretKeySpec(k, "AES");
            Cipher enc = Cipher.getInstance("AES");
            enc.init(Cipher.DECRYPT_MODE, key);
            CipherOutputStream cos = new CipherOutputStream(outStream, enc);
            byte[] buf = new byte[1024];
            int read;
            while((read=file.read(buf))!=-1)
            {
                cos.write(buf,0,read);
            }
            file.close();
            outStream.flush();
            cos.close();
            JOptionPane.showMessageDialog(null, "Your file is   Decrypted Sucessfully");
          //  Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler"+"Decrypted.txt");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Try again or Check the length of Secrect Key");
        }
    }//GEN-LAST:event_decrypt_fileActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new decrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton choose_file;
    private javax.swing.JButton decrypt_file;
    private javax.swing.JTextField filepath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField secrect_key;
    // End of variables declaration//GEN-END:variables
}
